version: "3.8"

services:
  bot:
    build: .
    container_name: autobot-rpa
    volumes:
      - ./output:/app/output
      - ./data/logs:/app/data/logs
      - ./clients:/app/clients
    env_file:
      - .env
    shm_size: "2gb"
    environment:
      - DISPLAY=:99
    command: ["--client-id", "demo_mercado_livre"]
